### User Registration Test 2
POST http://localhost:8081/api/users/register
Content-Type: application/json

{
  "name": "Hirushan Lakshitha",
  "email": "hirushan2@example.com",
  "password": "password123s",
  "englishLevel": "INTERMEDIATE"
}